# Generated by Django 6.0.1 on 2026-01-10 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentperiod',
            name='books_sold',
        ),
    ]
