# Generated by Django 6.0.1 on 2026-01-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_paymentperiod_books_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentperiod',
            name='manual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override the calculated amount with a manual value', max_digits=10, null=True),
        ),
    ]
