# Generated by Django 6.0.1 on 2026-01-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_packed',
            field=models.BooleanField(default=False),
        ),
    ]
